#!/usr/bin/env python3
"""
sprites_to_header.py — pack the cleaned Carl sprites into carl_sprites.h.

Each PNG is composited over Carl's flat background color, converted to RGB565,
and RLE-compressed (these flat-color cartoons squash to a few percent of raw).
On the device we decode the RLE back into PSRAM buffers at boot for fast blits.

RLE stream = flat uint16 array of [count, value, count, value, ...].

Usage (via the venv):
    tools/.venv/bin/python tools/sprites_to_header.py --in sprites --out carl_sprites.h
"""
import argparse
import os
import sys

import numpy as np
from PIL import Image

# filename base -> (enum id, C identifier), in display order
ORDER = [
    ("carl_neutral",  "SP_NEUTRAL"),
    ("carl_happy",    "SP_HAPPY"),
    ("carl_dizzy",    "SP_DIZZY"),
    ("carl_sleepy",   "SP_SLEEPY"),
    ("carl_thinking", "SP_THINKING"),
    ("carl_butt",     "SP_BUTT"),
]


def rgb565(arr):
    r = (arr[..., 0].astype(np.uint16) & 0xF8) << 8
    g = (arr[..., 1].astype(np.uint16) & 0xFC) << 3
    b = (arr[..., 2].astype(np.uint16) >> 3)
    return (r | g | b).astype(np.uint16)


def composite(im, bg):
    """Flatten RGBA over a solid bg -> opaque RGB."""
    a = np.asarray(im).astype(np.float32)
    alpha = a[..., 3:4] / 255.0
    rgb = a[..., :3] * alpha + np.array(bg, np.float32) * (1 - alpha)
    return rgb.round().astype(np.uint8)


def rle_encode(flat):
    """flat: 1-D uint16 array -> list of (count, value), runs split at 65535."""
    out = []
    n = len(flat)
    i = 0
    while i < n:
        v = flat[i]
        j = i + 1
        while j < n and flat[j] == v and (j - i) < 65535:
            j += 1
        out.append((j - i, int(v)))
        i = j
    return out


def rle_decode(pairs, n):
    buf = np.empty(n, np.uint16)
    k = 0
    for count, value in pairs:
        buf[k:k + count] = value
        k += count
    return buf


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="indir", default="sprites")
    ap.add_argument("--out", dest="outfile", default="carl_sprites.h")
    ap.add_argument("--bg", default="74,110,105", help="background r,g,b (must match sketch C_BG)")
    args = ap.parse_args()
    bg = tuple(int(x) for x in args.bg.split(","))

    lines = [
        "// carl_sprites.h — AUTO-GENERATED by tools/sprites_to_header.py. Do not edit by hand.",
        "// RLE-compressed RGB565 Carl sprites; decoded into PSRAM at boot.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"// sprites flattened over background rgb{bg} (== sketch C_BG)",
        "",
    ]
    defs = []
    total_words = 0
    total_raw = 0

    for base, enum in ORDER:
        path = os.path.join(args.indir, base + ".png")
        if not os.path.exists(path):
            sys.exit(f"missing {path}")
        im = Image.open(path).convert("RGBA")
        w, h = im.size
        rgb = composite(im, bg)
        px = rgb565(rgb).reshape(-1)
        pairs = rle_encode(px)

        # verify round-trip before we trust it on-device
        assert np.array_equal(rle_decode(pairs, w * h), px), f"RLE mismatch for {base}"

        words = []
        for c, v in pairs:
            words.append(c)
            words.append(v)
        total_words += len(words)
        total_raw += w * h

        name = base + "_rle"
        lines.append(f"static const uint16_t {name}[] PROGMEM = {{")
        for i in range(0, len(words), 16):
            chunk = ",".join(str(x) for x in words[i:i + 16])
            lines.append("  " + chunk + ",")
        lines.append("};")
        lines.append("")
        defs.append((enum, name, len(words), w, h, len(pairs)))
        print(f"  {base:<16} {w}x{h}  {len(pairs):>6} runs  {len(words)*2//1024:>4} KB "
              f"(raw {w*h*2//1024} KB)")

    lines.append("enum SpriteId { " + ", ".join(e for e, *_ in defs) + ", SP_COUNT };")
    lines.append("")
    lines.append("struct SpriteDef { const uint16_t* rle; uint32_t words; uint16_t w, h; };")
    lines.append("static const SpriteDef CARL_SPRITES[SP_COUNT] = {")
    for enum, name, nwords, w, h, _ in defs:
        lines.append(f"  {{ {name}, {nwords}, {w}, {h} }},  // {enum}")
    lines.append("};")
    lines.append("")

    with open(args.outfile, "w") as f:
        f.write("\n".join(lines))

    print(f"\nWrote {args.outfile}: {total_words*2//1024} KB compressed "
          f"(raw would be {total_raw*2//1024} KB) — {6} sprites")


if __name__ == "__main__":
    main()
